version: '3.8'

services:
  # --------------------------------------------------------------------------------
  postgresdb:
    image: postgres:13-alpine
    container_name: postgresdb
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    restart: always
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - intranet
  # --------------------------------------------------------------------------------
  kratos-migrate:
    image: oryd/kratos:v0.6.0-alpha.2
    container_name: kratos-migrate
    environment:
      - DSN=postgres://test:test@postgresdb:5432/test?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos/config
        target: /etc/config/kratos
    command: ['migrate', 'sql', '--read-from-env', '--config', '/etc/config/kratos/kratos.yml', '--yes']
    networks:
      - intranet
    depends_on:
      - postgresdb
  # --------------------------------------------------------------------------------
  kratos:
    image: oryd/kratos:v0.6.0-alpha.2
    container_name: kratos
    environment:
      - DSN=postgres://test:test@postgresdb:5432/test?sslmode=disable&max_conns=20&max_idle_conns=4
    command: ['serve', '--config', '/etc/config/kratos/kratos.yml', '--dev']
    volumes:
      - type: bind
        source: ./kratos/config
        target: /etc/config/kratos
    ports:
      - 4434:4434
      - 4433:4433
    networks:
      - intranet
    depends_on:
      - postgresdb
      - kratos-migrate
  # --------------------------------------------------------------------------------
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: mailslurper
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
  # --------------------------------------------------------------------------------

volumes:
  postgresdb-data:

networks:
  intranet:
    driver: bridge
